#  https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
spring:
  jpa:
    show-sql: true
    open-in-view: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      #  http://docs.jboss.org/hibernate/orm/5.3/userguide/html_single/Hibernate_User_Guide.html#configurations
      hibernate:
        format_sql: true
        default_batch_fetch_size: 20
        # https://stackoverflow.com/questions/21257819/what-is-the-difference-between-hibernate-jdbc-fetch-size-and-hibernate-jdbc-batc
        jdbc.batch_size: 20
        column_ordering_strategy: legacy
  datasource:
    #InMemory
    url: jdbc:h2:mem:booksharing
    tcp: jdbc:h2:tcp://localhost:9092/mem:booksharing
    username: sa
    password:
  h2.console.enabled: false

# Jackson Serialization Issue Resolver
  jackson.visibility:
    field: any
    getter: none
    setter: none
    is-getter: none
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
    # https://stackoverflow.com/questions/11757487/how-to-tell-jackson-to-ignore-a-field-during-serialization-if-its-value-is-null
    default-property-inclusion: non_empty

logging:
  level:
    root: WARN
    com.example.booksharingapp: DEBUG
    org.springframework.security.web.FilterChainProxy: DEBUG

springdoc.swagger-ui.path: /

